-- Examik — language exams (IELTS / TOEFL / Duolingo), plan Block 2 proof.
-- Run AFTER 04_qualifications.sql. This adds THREE new exams with ZERO app code:
-- one row each in `qualifications` + their section rows in `curriculum`. Once run,
-- the client (qualifications-store.jsx + curriculum-store.jsx) surfaces them in
-- the picker and builds a full section course — proving "exam without code".
-- Re-run-safe: deletes these ids first, so running twice never duplicates.

begin;

delete from public.qualifications where id in ('ielts','toefl','duolingo');
delete from public.curriculum     where qualification_id in ('ielts','toefl','duolingo');

insert into public.qualifications (id, label, emoji, blurb, board, board_options, education_system_id, grade_config, subject_presets, section_based, en_medium, default_for_countries, sort_order) values ('ielts', 'IELTS', '🌐', '{"en":"Bands 0–9","uk":"Бали 0–9","ru":"Баллы 0–9","fr":"Bandes 0–9","de":"Bänder 0–9"}'::jsonb, null, null, 'language', '{"kind":"score","min":0,"max":9,"step":0.5,"current":6,"target":7.5}'::jsonb, '["Listening","Reading","Writing","Speaking"]'::jsonb, true, false, '[]'::jsonb, 20);
insert into public.qualifications (id, label, emoji, blurb, board, board_options, education_system_id, grade_config, subject_presets, section_based, en_medium, default_for_countries, sort_order) values ('toefl', 'TOEFL', '🌐', '{"en":"iBT 0–120","uk":"iBT 0–120","ru":"iBT 0–120","fr":"iBT 0–120","de":"iBT 0–120"}'::jsonb, null, null, 'language', '{"kind":"score","min":0,"max":120,"step":1,"current":80,"target":100}'::jsonb, '["Reading","Listening","Speaking","Writing"]'::jsonb, true, false, '[]'::jsonb, 21);
insert into public.qualifications (id, label, emoji, blurb, board, board_options, education_system_id, grade_config, subject_presets, section_based, en_medium, default_for_countries, sort_order) values ('duolingo', 'Duolingo', '🦉', '{"en":"DET 10–160","uk":"DET 10–160","ru":"DET 10–160","fr":"DET 10–160","de":"DET 10–160"}'::jsonb, null, null, 'language', '{"kind":"score","min":10,"max":160,"step":5,"current":105,"target":130}'::jsonb, '["Literacy","Comprehension","Conversation","Production"]'::jsonb, true, false, '[]'::jsonb, 22);

insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'ielts', null, 'standard', 'Listening', '["Listening"]'::jsonb, '[{"name":"Section 1: Everyday conversation","difficulty":5,"importance":7,"subtopics":["Form completion","Note completion","Multiple choice"]},{"name":"Section 2: Monologue","difficulty":5,"importance":6,"subtopics":["Map/plan labelling","Matching","Sentence completion"]},{"name":"Section 3: Academic discussion","difficulty":5,"importance":7,"subtopics":["Multiple choice","Matching","Flow-chart completion"]},{"name":"Section 4: Academic lecture","difficulty":5,"importance":8,"subtopics":["Note completion","Summary completion","Table completion"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'ielts', null, 'standard', 'Reading', '["Reading"]'::jsonb, '[{"name":"Skimming and scanning","difficulty":5,"importance":7,"subtopics":["Locating information","Reading for gist"]},{"name":"True / False / Not Given","difficulty":5,"importance":8,"subtopics":["Fact vs claim","Distractors"]},{"name":"Matching headings","difficulty":5,"importance":7,"subtopics":["Paragraph main idea","Summarising"]},{"name":"Sentence and summary completion","difficulty":5,"importance":7,"subtopics":["Keyword spotting","Paraphrase"]},{"name":"Multiple choice","difficulty":5,"importance":6,"subtopics":["Detail questions","Inference"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'ielts', null, 'standard', 'Writing', '["Writing"]'::jsonb, '[{"name":"Task 1: Report from visual data","difficulty":5,"importance":8,"subtopics":["Describing trends","Comparing data","Overview sentence"]},{"name":"Task 2: Opinion / argument essay","difficulty":5,"importance":9,"subtopics":["Thesis and structure","Developing arguments","Conclusion"]},{"name":"Coherence and cohesion","difficulty":5,"importance":7,"subtopics":["Linking devices","Paragraphing"]},{"name":"Lexical resource","difficulty":5,"importance":7,"subtopics":["Topic vocabulary","Collocations"]},{"name":"Grammatical range and accuracy","difficulty":5,"importance":7,"subtopics":["Complex sentences","Tense control"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'ielts', null, 'standard', 'Speaking', '["Speaking"]'::jsonb, '[{"name":"Part 1: Introduction and interview","difficulty":5,"importance":6,"subtopics":["Familiar topics","Short answers"]},{"name":"Part 2: Long turn (cue card)","difficulty":5,"importance":8,"subtopics":["Structuring 2 minutes","Note-making"]},{"name":"Part 3: Two-way discussion","difficulty":5,"importance":8,"subtopics":["Abstract ideas","Justifying opinions"]},{"name":"Fluency and coherence","difficulty":5,"importance":7,"subtopics":["Reducing hesitation","Discourse markers"]},{"name":"Pronunciation","difficulty":5,"importance":6,"subtopics":["Stress and intonation","Individual sounds"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'toefl', null, 'standard', 'Reading', '["Reading"]'::jsonb, '[{"name":"Factual and negative factual information","difficulty":5,"importance":7,"subtopics":["Detail questions","Exception questions"]},{"name":"Inference and rhetorical purpose","difficulty":5,"importance":8,"subtopics":["Author intent","Implied meaning"]},{"name":"Vocabulary in context","difficulty":5,"importance":6,"subtopics":["Academic word list","Synonyms"]},{"name":"Sentence simplification","difficulty":5,"importance":7,"subtopics":["Core meaning","Removing detail"]},{"name":"Prose summary","difficulty":5,"importance":8,"subtopics":["Main ideas","Excluding minor points"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'toefl', null, 'standard', 'Listening', '["Listening"]'::jsonb, '[{"name":"Academic lectures","difficulty":5,"importance":8,"subtopics":["Note-taking","Signposting language"]},{"name":"Campus conversations","difficulty":5,"importance":6,"subtopics":["Problem/solution","Gist and detail"]},{"name":"Connecting content","difficulty":5,"importance":7,"subtopics":["Organisation questions","Attitude questions"]},{"name":"Function and stance","difficulty":5,"importance":7,"subtopics":["Speaker purpose","Certainty and opinion"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'toefl', null, 'standard', 'Speaking', '["Speaking"]'::jsonb, '[{"name":"Independent task","difficulty":5,"importance":8,"subtopics":["Personal preference","45-second response"]},{"name":"Integrated: read-listen-speak","difficulty":5,"importance":9,"subtopics":["Synthesising sources","Note integration"]},{"name":"Integrated: listen-speak","difficulty":5,"importance":8,"subtopics":["Summarising a lecture","Delivery timing"]},{"name":"Delivery and language use","difficulty":5,"importance":7,"subtopics":["Pace and clarity","Grammar and vocabulary"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'toefl', null, 'standard', 'Writing', '["Writing"]'::jsonb, '[{"name":"Integrated writing","difficulty":5,"importance":9,"subtopics":["Reading + lecture synthesis","Paraphrasing"]},{"name":"Writing for an academic discussion","difficulty":5,"importance":8,"subtopics":["Stating a position","Supporting with reasons"]},{"name":"Development and organisation","difficulty":5,"importance":7,"subtopics":["Topic sentences","Transitions"]},{"name":"Language use","difficulty":5,"importance":7,"subtopics":["Sentence variety","Accuracy"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'duolingo', null, 'standard', 'Literacy', '["Literacy"]'::jsonb, '[{"name":"Read and complete (c-test)","difficulty":5,"importance":7,"subtopics":["Word completion","Context clues"]},{"name":"Read and select real words","difficulty":5,"importance":6,"subtopics":["Vocabulary breadth","Spelling"]},{"name":"Interactive reading","difficulty":5,"importance":8,"subtopics":["Detail and inference","Ordering ideas"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'duolingo', null, 'standard', 'Comprehension', '["Comprehension"]'::jsonb, '[{"name":"Listen and type (dictation)","difficulty":5,"importance":7,"subtopics":["Sound-to-spelling","Chunking"]},{"name":"Interactive listening","difficulty":5,"importance":8,"subtopics":["Conversation flow","Summary response"]},{"name":"Read then respond","difficulty":5,"importance":7,"subtopics":["Main idea","Supporting detail"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'duolingo', null, 'standard', 'Conversation', '["Conversation"]'::jsonb, '[{"name":"Interactive speaking","difficulty":5,"importance":8,"subtopics":["Answering prompts","Follow-up questions"]},{"name":"Speak about the photo","difficulty":5,"importance":7,"subtopics":["Description","Fluency"]},{"name":"Read aloud","difficulty":5,"importance":6,"subtopics":["Pronunciation","Intonation"]}]'::jsonb, 'official');
insert into public.curriculum (country_id, education_system_id, qualification_id, board, spec_version, subject, aliases, topics, source) values ('', 'language', 'duolingo', null, 'standard', 'Production', '["Production"]'::jsonb, '[{"name":"Writing sample","difficulty":5,"importance":8,"subtopics":["Task response","Organisation"]},{"name":"Speaking sample","difficulty":5,"importance":8,"subtopics":["Extended response","Coherence"]},{"name":"Write about the photo","difficulty":5,"importance":7,"subtopics":["Detail and accuracy","Sentence variety"]}]'::jsonb, 'official');

commit;
