/**
 * Full English legal pages (Phase 6 pass, Decision Log #51 follow-up).
 * Drafted from the actual architecture (Supabase/Vercel/Anthropic/OpenAI
 * fallback/Resend/OneSignal/Stripe, RLS isolation, Settings delete-account
 * flow, 3-day trial on every paid tier, web-only Stripe checkout — no
 * Apple IAP). Not a substitute for a lawyer: see legal_stub_en in landing.ts
 * for the disclaimer shown above every page. uk/ru/fr/de stay the old
 * one-paragraph stub until translated (Decision: English first).
 *
 * Shape: LegalSection[] — { h?: heading, p: paragraph }. Legal.jsx renders
 * each entry; a bare `p` with no `h` continues the previous section.
 */

export type LegalSection = { h?: string; p: string };

const UPDATED = "20 August 2026";

export const LEGAL_PRIVACY_EN: LegalSection[] = [
  { h: "Who runs this", p: `Examik is operated by Hlib Pakhomov, a Ukrainian citizen studying Computer Systems Engineering at the University of Warwick in the UK on a Student visa — an individual, not a registered company. This policy explains what Examik collects, why, and what you can do about it. Last updated ${UPDATED}.` },
  { h: "What we collect", p: "Account: email address and display name, created via Supabase Auth. Study data: your exam list, weekly schedule, mastery/XP progress, mistake journal, and any files or text you send the AI Coach (essays, photos of homework, chat transcripts). Notification preferences: which of the 7 email/push triggers you've enabled. Billing: your subscription tier and Stripe customer/subscription IDs — your card number never touches our servers, Stripe handles it directly." },
  { h: "Why we collect it", p: "To run the product: build your study schedule, grade your practice, remember what you got wrong, and let the AI Coach answer with context about where you are. We do not use your data for advertising, and we do not sell it to anyone." },
  { h: "Who else sees it", p: "Sub-processors, each only for what they're named for: Supabase (database + authentication, row-level security means one user's data is invisible to another user's queries), Vercel (hosting and the serverless functions your requests pass through), Anthropic (the Claude model that powers the AI Coach — receives the message you send it and the study context needed to answer well), OpenAI (emergency-only fallback if Anthropic is unreachable — same message content, used only when the primary provider fails), Resend (sends the transactional emails you've opted into), OneSignal (web push, only if you granted the browser permission), Stripe (payment processing for Pro/Ultra). None of them may use your data for their own purposes." },
  { h: "AI-generated study content", p: "Practice questions the AI generates get checked against a shared question bank (by hash and by similarity) so two students don't see identical AI-written questions back to back. That bank stores the question text and which exam/topic it's for — not your name or account." },
  { h: "How long we keep it", p: "For as long as your account exists. Delete your account in Settings and both your study data and your Supabase Auth account are removed. Some records (like Stripe invoices) are kept as long as tax law requires us to keep them, independent of your Examik account." },
  { h: "Your rights", p: "Access, correct, export, or delete your data — most of this is self-service in Settings; anything that isn't, email us and we'll handle it by hand. If you're in the UK or EU you also have the right to object to processing and to complain to your local data protection authority (the ICO, in the UK) if you think we've got something wrong." },
  { h: "Security", p: "Everything runs over HTTPS. Your data is isolated per-user at the database level (Postgres row-level security), not just in application code. AI API keys live server-side only — they are never shipped to your browser." },
  { h: "Children", p: "Examik is for students aged 13 and up. See the separate Children's Privacy page for details." },
  { h: "Changes", p: "If this policy changes in a way that matters, we'll say so on this page and, for material changes, email you." },
  { h: "Contact", p: "Questions, requests, or a conflict with your country's law: reach out through the contact details on the landing page and we'll sort it out." },
];

export const LEGAL_TERMS_EN: LegalSection[] = [
  { h: "What Examik is", p: `A study tool for standardised exam prep (NMT, SAT, IELTS, TOEFL, Duolingo English Test, GCSE, A-Level, ЗНО, and others as we add them). It does not guarantee a score, a grade, or admission anywhere. Last updated ${UPDATED}.` },
  { h: "The AI can be wrong", p: "Practice questions, explanations, and scores are generated by an AI model. Treat them as practice, not as an authoritative source — always check the official syllabus or past papers from your actual exam board for what really counts." },
  { h: "Acceptable use", p: "Examik is for studying, not for live-exam misconduct — do not use it to cheat during an actual sitting. Do not attempt to extract, scrape, or resell the question bank, abuse the API (automated hammering, credential sharing to dodge quota), or use the service to generate content unrelated to exam study." },
  { h: "Accounts", p: "You're responsible for your account's security. One person, one account — do not share logins to get around per-account limits. We may suspend or close an account that abuses the service, without it entitling you to a refund for the abused period." },
  { h: "Subscriptions", p: "Pro and Ultra are paid tiers with a 3-day free trial, billed monthly or yearly at the price shown at checkout. Cancel any time before the trial ends and you're not charged. See the Refund policy for what happens after you are." },
  { h: "Your content", p: "You keep ownership of anything you upload (essays, photos, notes). You grant us the licence needed to process it — send it to the AI model, store it, show it back to you — for the sole purpose of running the service." },
  { h: "No warranty", p: "The service is provided as-is. We work to keep it accurate and available, but we don't promise it will be error-free, uninterrupted, or fit for any specific exam board's requirements." },
  { h: "Liability", p: "To the extent the law allows, we are not liable for exam outcomes, missed deadlines, or indirect losses arising from using or being unable to use Examik. Nothing here limits liability the law doesn't let us limit." },
  { h: "Changes to these terms", p: "We may update these terms as the product changes. Material changes get flagged on this page." },
  { h: "Governing law", p: "These terms are governed by the law of England and Wales, without prejudice to any mandatory consumer-protection rights you have under the law of the country you live in." },
];

export const LEGAL_EULA_EN: LegalSection[] = [
  { h: "What you're licensed to do", p: `A personal, non-transferable licence to use the Examik app and website for your own exam preparation. This is a licence to use the software, not a sale of it, and not a licence to the underlying code. Last updated ${UPDATED}.` },
  { h: "What you're not licensed to do", p: "Reverse-engineer, decompile, or attempt to extract the source code, model prompts, or question bank; resell or sublicense access; use the app in a way that violates these terms or the Terms of Service." },
  { h: "iOS specifically", p: "The iOS build additionally follows Apple's standard EULA (the one in Apple's App Store Terms) to the extent that agreement isn't superseded by this one. Examik does not sell subscriptions via Apple In-App Purchase — Pro/Ultra are managed entirely on examik.net, on the web, outside the app." },
  { h: "Lesson content", p: "Theory, practice questions, and explanations in the Learn section are generated by an AI model against a syllabus we've drafted or AI-drafted and reviewed — they are not an official publication of any ministry of education or exam board, and should be checked against the real syllabus." },
  { h: "Termination", p: "This licence ends automatically if you violate its terms, or when you delete your account. Ending the licence doesn't undo anything you've already been charged for — see the Refund policy for that." },
];

export const LEGAL_REFUND_EN: LegalSection[] = [
  { h: "The trial", p: "Every paid tier (Pro, Ultra) starts with a 3-day free trial. Cancel any time during those 3 days in Settings and you are not charged anything." },
  { h: "After the trial", p: "Once the trial ends, your card is charged the price shown at checkout for the plan and billing period (monthly or yearly) you picked. Recurring charges after that follow the same cadence until you cancel." },
  { h: "Cancelling", p: "Cancel any time in Settings → Subscription, or via the billing portal linked there. Cancelling stops future renewals; it does not automatically refund the period already paid for." },
  { h: "Refund window", p: "If you're within 14 days of a charge (the trial-to-paid conversion or any renewal) and you didn't mean to be charged, or the service materially didn't work for you, contact us and we'll refund it — no interrogation, no fine print beyond this paragraph." },
  { h: "Outside the window", p: "Past 14 days we generally don't refund a completed billing period, but we'll still look at genuine problems (a billing error on our end, a service outage that ate your study time) case by case." },
  { h: "How refunds are paid", p: "Refunds go back to the original payment method via Stripe, typically within 5–10 business days depending on your bank." },
  { h: "No App Store billing yet", p: "There is currently no Apple In-App Purchase for Pro/Ultra — all billing runs through Stripe on the web, so Apple's own refund process doesn't apply here." },
];

export const LEGAL_COOKIES_EN: LegalSection[] = [
  { h: "What we actually use", p: "A Supabase session cookie/token that keeps you logged in. Your language, theme, and other preferences in localStorage on your device (never sent anywhere except back to our own servers when relevant). A OneSignal identifier, only if you explicitly granted browser push permission." },
  { h: "What we don't use", p: "No third-party advertising trackers, no cross-site tracking pixels, no Google Analytics or equivalent, anywhere on the landing page or the app. If that ever changes, it'll be a separate, disclosed decision — not silently added." },
  { h: "Managing this", p: "Clearing your browser's storage logs you out and resets local preferences. Revoking push permission in your browser settings stops the OneSignal identifier being used." },
];

export const LEGAL_CHILDREN_EN: LegalSection[] = [
  { h: "Age", p: "Examik is intended for students aged 13 and up. If you're younger than 13, please don't create an account — ask a parent or guardian to help you find an age-appropriate alternative." },
  { h: "Parents and guardians", p: "If you believe a child under 13 has created an account or given us personal data, contact us and we will delete it. Because many of our exams (GCSE, ЗНО, A-Level) are taken by students who are minors under the law of their country even though they're 13+, we keep the data we collect from teenage users to the minimum the product actually needs — study progress and account basics, not behavioural profiling." },
  { h: "Regional differences", p: "The age at which a young person can consent to an online service on their own varies by country (13 in the UK and US; up to 16 in some EU member states). If your country sets a higher age than 13, that age applies to you, and a parent or guardian should set up the account instead." },
];
