// Syllabus pipeline — step 7: seeder (deliverables #5/#8).
//
//   node scripts/syllabus/seed.mjs syllabus-data/<exam>.normalized.json
//
// Turns a reviewed <exam>.normalized.json into an idempotent SQL migration at
// supabase/seed/07_syllabus_<exam>.sql. Run that file in the Supabase SQL editor
// (postgres bypasses RLS) to make the syllabus live. Re-run-safe: it deletes the
// exam's sections first (cascades to topics/subtopics/links) and every id is a
// deterministic UUIDv5, so running twice converges instead of duplicating.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ids, sqlStr, sqlUuid, sqlInt, sqlTextArray, slugify } from "./lib.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const inPath = process.argv[2];
if (!inPath) { console.error("usage: node seed.mjs <exam>.normalized.json"); process.exit(1); }
const d = JSON.parse(readFileSync(inPath, "utf8"));
const exam = d.exam;
const L = []; // sql lines

L.push(`-- AI Exam Coach — syllabus seed for '${exam}' (generated by scripts/syllabus/seed.mjs).`);
L.push(`-- Run AFTER 06_syllabus_schema.sql. Idempotent: deletes this exam's syllabus`);
L.push(`-- first (cascades), deterministic ids, so re-running never duplicates.`);
L.push(`-- Requires a qualifications row with id='${exam}' (04/05 migrations).`);
L.push(`begin;`);
L.push(`delete from public.syllabus_sections where exam_id = ${sqlStr(exam)};`);
L.push("");

// sources (global; idempotent by id)
L.push(`-- sources`);
for (const s of d.sources || []) {
  const id = ids.source(exam, s.key);
  L.push(`insert into public.syllabus_sources (id, name, type, url, retrieved_at, notes) values (` +
    `${sqlUuid(id)}, ${sqlStr(s.name)}, ${sqlStr(s.type)}, ${sqlStr(s.url)}, coalesce(${sqlStr(s.retrieved_at)}::timestamptz, now()), ${sqlStr(s.notes)}) ` +
    `on conflict (id) do nothing;`);
}
L.push("");

// skills (global; idempotent by slug)
L.push(`-- skills (global, reusable across exams)`);
for (const sk of d.skills || []) {
  L.push(`insert into public.syllabus_skills (id, slug, name, description) values (` +
    `${sqlUuid(ids.skill(sk.slug))}, ${sqlStr(sk.slug)}, ${sqlStr(sk.name)}, ${sqlStr(sk.description)}) ` +
    `on conflict (slug) do nothing;`);
}
L.push("");

const srcId = (key) => (key ? sqlUuid(ids.source(exam, key)) : "null");

// sections + topics + subtopics
for (const sec of d.sections || []) {
  const secId = ids.section(exam, sec.slug);
  L.push(`-- ── section: ${sec.name} ──`);
  L.push(`insert into public.syllabus_sections (id, exam_id, slug, name, description, sort_order, source_id, tags, est_study_minutes) values (` +
    `${sqlUuid(secId)}, ${sqlStr(exam)}, ${sqlStr(sec.slug)}, ${sqlStr(sec.name)}, ${sqlStr(sec.description)}, ${sqlInt(sec.sort_order)}, ${srcId(sec.source)}, ${sqlTextArray(sec.tags)}, ${sqlInt(sec.est_study_minutes)});`);
  for (const t of sec.topics || []) {
    const topicId = ids.topic(exam, sec.slug, t.slug);
    L.push(`insert into public.syllabus_topics (id, section_id, slug, name, description, difficulty, sort_order, source_id, tags, est_study_minutes) values (` +
      `${sqlUuid(topicId)}, ${sqlUuid(secId)}, ${sqlStr(t.slug)}, ${sqlStr(t.name)}, ${sqlStr(t.description)}, ${sqlInt(t.difficulty)}, ${sqlInt(t.sort_order)}, ${srcId(t.source)}, ${sqlTextArray(t.tags)}, ${sqlInt(t.est_study_minutes)});`);
    for (const st of t.subtopics || []) {
      L.push(`insert into public.syllabus_subtopics (id, topic_id, slug, name, difficulty, sort_order) values (` +
        `${sqlUuid(ids.subtopic(exam, sec.slug, t.slug, st.slug))}, ${sqlUuid(topicId)}, ${sqlStr(st.slug)}, ${sqlStr(st.name)}, ${sqlInt(st.difficulty)}, ${sqlInt(st.sort_order)});`);
    }
    for (const skSlug of t.skills || []) {
      L.push(`insert into public.syllabus_topic_skills (topic_id, skill_id) values (${sqlUuid(topicId)}, ${sqlUuid(ids.skill(skSlug))}) on conflict do nothing;`);
    }
    for (const alias of t.aliases || []) {
      L.push(`insert into public.syllabus_topic_aliases (topic_id, alias) values (${sqlUuid(topicId)}, ${sqlStr(alias)}) on conflict do nothing;`);
    }
  }
  L.push("");
}

// prerequisites — resolved AFTER all topics exist. Prereq refs are topic slugs;
// we need the (section, topic) each slug belongs to. Build a slug→section map.
const topicSection = new Map();
for (const sec of d.sections || []) for (const t of sec.topics || []) topicSection.set(t.slug, sec.slug);
L.push(`-- prerequisites (topic DAG)`);
for (const sec of d.sections || []) for (const t of sec.topics || []) {
  for (const preSlug of t.prerequisites || []) {
    const preSec = topicSection.get(preSlug);
    if (!preSec) { L.push(`-- skipped unknown prerequisite '${preSlug}' for topic '${t.slug}'`); continue; }
    const topicId = ids.topic(exam, sec.slug, t.slug);
    const preId = ids.topic(exam, preSec, preSlug);
    L.push(`insert into public.syllabus_topic_prerequisites (topic_id, prerequisite_topic_id) values (${sqlUuid(topicId)}, ${sqlUuid(preId)}) on conflict do nothing;`);
  }
}

L.push("");
L.push("commit;");

const outDir = join(HERE, "..", "..", "supabase", "seed");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, `07_syllabus_${slugify(exam)}.sql`);
writeFileSync(outPath, L.join("\n") + "\n");
const nTopics = (d.sections || []).reduce((n, s) => n + (s.topics || []).length, 0);
console.log(`✓ seed for '${exam}': ${(d.sections || []).length} sections, ${nTopics} topics → ${outPath.replace(/.*\/supabase\//, "supabase/")}`);
